#
# Pipeline that copies notebook from one workspace to another
#
name: mlops_template_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
 branches:
   include:
     - release*

pr:
  branches:
    include:
     - main
  paths:
    exclude:
    - README.md
Variables:
  - name: reference
    value: $(Build.SourceBranch)
resources:
  repositories:
    - repository: MlApp
      type: github
      name: sugamg/si-template
      endpoint: MyGit
      ref: $(reference)

    - repository: MlOps
      type: github
      name: sugamg/si-ml-ops
      endpoint: MyGit
      ref: main

stages:          
# Call the stages in the MlOps repo 
    - template: databricks-ml/pipelines/stages/mlops-main-stage.yml@MlOps  # Template reference
